zflist-publish: check input username match with logged in username

diff --git a/.github/workflows/zflist-publish b/.github/workflows/zflist-publish
--- a/.github/workflows/zflist-publish
+++ b/.github/workflows/zflist-publish
@@ -15,6 +15,15 @@ if [ "$INPUT_TOKEN" != "" ]; then
     
     ZFLIST_HUB_TOKEN=$(zflist hub refresh)
 
+    zflist login
+    username=$(zflist hub username)
+
+    if [ "$username" != "$INPUT_USER" ]; then
+        echo "Error: requested username not authorized with this token"
+        echo "Error: logged in: $username, requested: $INPUT_USER"
+        exit 1
+    fi
+
     export ZFLIST_BACKEND="{\"host\": \"hub.grid.tf\", \"port\": 9980, \"token\": \"$ZFLIST_HUB_TOKEN\"}"
 fi
 
