zflist-publish: ensure token get refreshed

diff --git a/.github/workflows/zflist-publish b/.github/workflows/zflist-publish
--- a/.github/workflows/zflist-publish
+++ b/.github/workflows/zflist-publish
@@ -13,7 +13,11 @@ if [ "$INPUT_TOKEN" != "" ]; then
     export ZFLIST_HUB_TOKEN=$INPUT_TOKEN
     export ZFLIST_HUB_USER=$INPUT_USER
     
-    export ZFLIST_HUB_TOKEN=$(zflist hub refresh)
+    ZFLIST_HUB_TOKEN=$(zflist hub refresh)
+    if [ $? == 1 ]; then
+        echo "Could not refresh hub token, is the token valid ?"
+        exit 1
+    fi
 
     if [ "$ZFLIST_HUB_USER" != "" ]; then
         echo "Checking logged in username (expected: $ZFLIST_HUB_USER)"
